name: Upload Python Package
on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: abatilo/actions-poetry@v2.1.0
    - name: Get version & setup version
      run: |
        version=${{ github.event.release.tag_name }}
        poetry version $version
        sed -i "s/__version__ = .*/__version__ = \"${version}\"/g" ./pytest_rocketchat/__init__.py
    - name: Bump version & Commit
      uses: EndBug/add-and-commit@v7.1.2
      with:
        add: '["pyproject.toml", "pytest_rocketchat/__init__.py"]'
        branch: 'master'
        message: 'bump version up to ${{ github.event.release.tag_name }}'
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.5
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        build_format: 'wheel'
